import { readdirSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { sha256, splitVendored, UPSTREAM } from '../../../scripts/sync-rekta.ts';

// Offline drift guard for the vendored Rekta Design tokens. Comparing against upstream needs the network and
// runs nightly (scripts/sync-rekta.ts --check); this suite only proves the file is what the sync wrote.

const vendoredText = readFileSync(new URL('./rekta.css', import.meta.url), 'utf8');
const vendored = splitVendored(vendoredText);
const declared = new Set(
	[...vendored.body.matchAll(/(--rekta-[\w-]+):/g)].map((match) => match[1])
);

function appSources(): { file: string; text: string }[] {
	const root = new URL('../../', import.meta.url);
	return readdirSync(root, { recursive: true, encoding: 'utf8' })
		.filter((file) => /\.(css|svelte|ts)$/.test(file))
		.filter((file) => !file.endsWith('.test.ts') && !file.endsWith('rekta.css'))
		.map((file) => ({ file, text: readFileSync(new URL(file, root), 'utf8') }));
}

describe('vendored rekta.css', () => {
	it('carries a provenance header with source, commit, hash, licence and the design system notice', () => {
		expect(vendoredText).toContain(` * Source: ${UPSTREAM}\n`);
		expect(vendored.commit).toMatch(/^[0-9a-f]{40}$/);
		expect(vendored.sha256).toMatch(/^[0-9a-f]{64}$/);
		expect(vendoredText).toContain(' * License: MIT');
		expect(vendoredText).toContain('Porsche Design System source code (Apache License 2.0)');
	});

	it('matches the SHA-256 in its header, so nobody edited the generated CSS by hand', () => {
		expect(sha256(vendored.body)).toBe(vendored.sha256);
	});

	it('starts its body with the generator line, so the header hides nothing of the generated file', () => {
		expect(vendored.body.startsWith('/* Generated by scripts/build-css.mjs')).toBe(true);
	});

	it('declares every --rekta-* variable that the app uses or overrides', () => {
		const unknown = appSources().flatMap(({ file, text }) =>
			[...text.matchAll(/--rekta-[\w-]+/g)]
				.map((match) => match[0])
				.filter((name) => !declared.has(name))
				.map((name) => `${file}: ${name}`)
		);
		expect(declared.size).toBeGreaterThan(50);
		expect(unknown).toEqual([]);
	});
});

describe('tokens.css on top of rekta.css', () => {
	const tokens = readFileSync(new URL('./tokens.css', import.meta.url), 'utf8');
	const declarationsIn = (rule: string) =>
		new Map([...rule.matchAll(/(--[\w-]+):\s*([^;]+);/g)].map((match) => [match[1], match[2]]));

	it('imports rekta.css before declaring anything, so its own names can build on it', () => {
		expect(tokens.indexOf("@import './rekta.css';")).toBeGreaterThan(0);
		expect(tokens.indexOf("@import './rekta.css';")).toBeLessThan(tokens.indexOf('\n:root {'));
	});

	it('points the tile, mark, type, weight and motion tokens and the UI font at Rekta values', () => {
		const root = declarationsIn(tokens.slice(tokens.indexOf('\n:root {'), tokens.indexOf('\n}')));
		const rektaBacked = [...root].filter(([name]) =>
			/^--(tile|mark|type|weight|motion)-|^--(rule|radius-tile|ease-base|font-sans)$/.test(name)
		);
		expect(rektaBacked.length).toBeGreaterThan(25);
		for (const [name, value] of rektaBacked) expect(value, name).toMatch(/^var\(--rekta-[\w-]+\)$/);
	});

	it('sets every Rekta duration to 0s under the in-app reduced motion setting', () => {
		const start = tokens.indexOf(":root[data-motion='reduced'] {");
		const reduced = declarationsIn(tokens.slice(start, tokens.indexOf('}', start)));
		const durations = [...declared].filter((name) => name.startsWith('--rekta-motion-duration-'));
		expect(durations).not.toHaveLength(0);
		for (const name of durations) expect(reduced.get(name), name).toBe('0s');
	});
});
